mozilla/remo

- remo/base/static/base/css/app-fd4.less
- remo/base/templates/includes/pagination.html
- remo/dashboard/templates/list_action_items.html
- remo/dashboard/tests/test_views.py
- remo/dashboard/views.py
- remo/featuredrep/models.py
- remo/featuredrep/static/featuredrep/js/featuredrep.js
- remo/featuredrep/templates/featuredrep_list.html
- remo/featuredrep/views.py
- remo/reports/templates/list_ng_reports.html
- remo/reports/tests/test_views.py
- remo/reports/views.py
- remo/voting/templates/list_votings.html
* Added pagination every 15 objects
* Until we have a more sane way to determine when a Rep was featured, it makes sense to sort them based on the `created_on` date.
> [fix bug 1104828] Add pagination and sorting to the ROM page

- remo/profiles/templates/profiles_list_alumni.html
This was left there due to the macro we initially had on the template. We missed it when we removed it.
> Fix Alumni missing pagination

- remo/events/forms.py
* Plain "cdata" dict lookup raises KeyError
* Add default=None and use cdata.get() instead
> [bug 1138847] Fix clean "categories" when no category is selected.

- remo/base/static/base/css/app-fd4.less
- remo/base/templates/main.html
In cases when we have more than one Featured Rep, we iterate the html block but we don't add a new row element.
This small refactoring adds a new row element for each Rep with `top-margined` class to add some space in between. Also moved the markdown Featured text inside the if block. No need to evaluate it if no current Featured Rep.
> Add some space between Featured Reps

- remo/api/serializers.py
- remo/api/urls.py
- remo/base/tests/test_base_utils.py
- remo/base/utils.py
- remo/events/api/serializers.py
- remo/events/api/views.py
- remo/events/tests/test_api.py
- remo/reports/api/views.py
- remo/reports/tests/test_api.py
* Add APIView with the stats required for the activities KPI
* Enable filtering on `country`, `functional_areas__name`, `campaign__name`
* Use a generic KPI serializer since output is similar to all endpoints
> [Fix bug 1144188] Expose API endpoint for activities KPI.

- remo/events/tests/test_api.py
- remo/reports/tests/test_api.py
Tests where failing because we only patched ``now`` in ``api/views.py`` namespace and not in ``base/utils.py``.
> Fix patching `django.utils.timezone.now` on kpi tests.

- remo/remozilla/tasks.py
- remo/remozilla/tests/test_tasks.py
* New Bugzilla REST api uses a different endpoint for comments
* Minor lint fixes
> Fix API `GET` method for bugzilla comments.

- remo/profiles/api/api_v1.py
Now with the Alumni group a few profiles are without a mentor. For example right now the /people in the dev instance is broken due to an empty mentor field.
> Allow empty mentor fields in API v1.

- remo/settings/base.py
changed link from public.etherpad-mozilla.org/padname  to public.etherpad-mozilla.org/p/padname
>  [fix bug 1216035] fix broken etherpad link on reps portal

- remo/events/tasks.py
This will fix a couple celery tracebacks when the title of an event has unicode chars. @johngian r?
> Unicode title for the event metrics mail reminders please.

- remo/reports/tests/test_views.py
This test randomly failed when redirect url was
http://testserver/reports/rep/UserProfile1079/?month=January&year=2011
instead of
http://testserver/reports/rep/UserProfile1079/?year=2011&month=January
> Make LegacyReportingTests.test_old_report_redirect test solid.

- .travis.yml
- remo/settings/localtravis.py
I's hopping that this would fix the `TemplateSyntaxError: ("unexpected 'end of statement block'",)` error but no luck. Anyway I think that not running a Cache during tests is the way to go, to ensure that all tests are independent from each other.
> DummyCache for Travis

- remo/voting/views.py
* Allow to users belonging to multiple groups to vote.
> [fix bug 1308910] Fix voting permissions.

- docker-compose.yml
Running migration made the mysql server gone away in docker. So need
to fix it by extending the maximum allowed package. by default it is 1M. So changing it to 2M will let the migration run smoothly.
@akatsoulas r?
> Fix migration problem in docker

- remo/profiles/forms.py
- remo/profiles/migrations/0004_userprofile_rotm_nominated_by.py
- remo/profiles/models.py
- remo/profiles/tasks.py
- remo/profiles/templates/profiles_view.jinja
- remo/profiles/views.py
So this patch will change as following
- Who nominate a user as rep of the month is saved in the database in `rotm_nominated_by` column
- A user would not able to nominate himself for reps of the month
So I have slightly change the logic in the template. There was a little bug in the logic that made the button available for all while the waffle flag `enable_rotm_tasks` is activated.
@akatsoulas r?
> [Bug 1313018] Save also the nominator of the Rep

- Dockerfile
Copy code after installing requirements because it means that if there is no changes to packages we only need to pull a 5MB layer (instead of 150MB with packages)
> Add code to Docker image

- docker/dev
@flamingspaz r?
AMQP is listed as the broker in the env-dist file but we don't have it as a dependency anywhere.
> Install rabbitmq-server in docker dev.

- remo/settings.py
There isn't anything wrong with the current configuration, but lets keep it consistent with mozillians.
> Only set SES access credentials when we don't want boto to figure it out

- docs/installation-docker.rst
- docs/installation-virtualenv.rst
- remo/base/templates/settings.jinja
- remo/profiles/api/api_v1.py
- remo/profiles/migrations/0009_auto_20171101_2202.py
- remo/profiles/models.py
- remo/profiles/templates/profiles_edit.jinja
- remo/profiles/templates/profiles_people.jinja
- remo/profiles/templates/profiles_view.jinja
This changes all the front-facing mentions in the following way:
* Mobiliser skills -> Mobilizers expertise
* Mobilisers interests -> Mobilizers learning interests
I haven't changed all the occurances (like variables, etc), just the front-facing strings and some that make it easier to search for just having the front-facing strings. This is definitely not perfect, but all I can do in this timeframe. We need to get this going ASAP. :/
> Change front-facing phrasing

- remo/profiles/templates/profiles_edit.jinja
* Fixes undefined behaviour when selecting mobilizing expertise / learning areas as they had the same ID
* Fixes the "for" reference of the labels (side effect of having the same id for entries in both modals)
@akatsoulas r?
> Fix undefined behaviour of mobilizer selection

- remo/profiles/apps.py
- remo/profiles/forms.py
- remo/profiles/migrations/0010_auto_20171221_0112.py
- remo/profiles/models.py
- remo/profiles/templates/profiles_edit.jinja
- remo/profiles/tests/test_models.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1070716
This is a work in progress.
The tests pass, however it doesn't work when I test this with a Council account. The field doesn't show up since the perm doesn't get applied to the council member. How can I make sure that existing users get that permission as well?
@akatsoulas not important right now, let's focus on the other PRs for now. However, once you have time, would love to learn more about this :)
> WIP: Bug 1070716 - Only allow Admin/Council to change mentor

- remo/dashboard/templates/dashboard_reps.jinja
- remo/dashboard/views.py
This does two things:
* Only shows actual mentees in the dashboard, not everybody that was ever a mentee and reported
* Also shows mentees that never have reported anything
> Bug 1315124 - Fix Activities in Dashboard

- remo/dashboard/templates/dashboard_reps.jinja
- remo/dashboard/views.py
* Enables "Reps without Mentors" section for Council and Peers members - previously Admin only
* Enables "Reps without profile" section for Council and Onboarding members - previously Admin only
> Bug 1436892 / Bug 1436891 - Enable sections on dashboard for specific groups
