remo/profiles/templates/profiles_view.html

[bug 1100802] Check if date_left_program exists in profile view template.

---

remo/base/helpers.py
remo/base/static/base/css/app-fd4.less
remo/reports/forms.py
remo/reports/static/reports/js/edit_ng_report.js
remo/reports/templates/edit_ng_report.html
remo/reports/templates/view_ng_report.html
remo/reports/tests/test_forms.py

* ChoiceField instead ModelMultipleChoiceField for contribution areas
* Campaign is now a required field
* Removed CSS/JS code that handled campaign show/hide

[Fix bug 1139878] Change report form fields to facilitate "initiatives".

---

remo/profiles/forms.py

Order user list by first_name in availability settings.

---

remo/events/api.py
remo/events/helpers.py
remo/events/static/events/js/events_list.js
remo/events/templates/list_events.html
remo/events/templates/view_event.html
remo/events/views.py

* Export initiatives in API v1.

[fix bug 1140335] Filter events by initiative.

---

docs/installation-virtualenv.rst

There is a typo in virtualEnv method , it is stating the user to make changes in vagrant machine which is not the case.

Bug 1163578

---

remo/base/static/base/css/app-fd4.less

[Fix bug 1162450] Change leaflet z-index to put it below modals

---

remo/profiles/models.py
remo/profiles/tests/test_models.py

[fix bug 1167529] Check that a user has a mentor before sending an

---

remo/events/migrations/0024_migrate_pads_to_etherpad_lite.py
remo/settings/base.py

[bug 12105555][bug 1210559] Migrate to etherpad lite.

---

remo/base/templates/base_fd4.html
remo/base/templates/includes/footer_fd4.html

Fix https://bugzilla.mozilla.org/show_bug.cgi?id=757890

[757890] support for print stylesheet

---

remo/events/migrations/0024_migrate_pads_to_etherpad_lite.py

[bug 1210555] Update the etherpad url for the migration.

---

remo/profiles/forms.py
remo/profiles/templates/profiles_view.html

[fix bug 1132035] Do not nominate for ROTM members of the Alumni group.

---

Dockerfile
remo/settings/local.py-docker-dist

Update settings for Docker.

---

remo/profiles/admin.py

* When a user joined the program.
* When a user left the program.

Update UserResouce to include more options.

---

remo/profiles/admin.py

Export display_name through the admin interface.

---

remo/profiles/templates/includes/alumni_msg.html
remo/profiles/views.py

[fix bug 1235984] Add a link to the Alumni page in alumni profiles.

---

remo/base/static/base/css/app-fd4.less

Now:
After:
https://bugzilla.mozilla.org/show_bug.cgi?id=1116023

[1116023] Display event time in user's local time on event pages

---

remo/events/admin.py

Use 'TabularInline' for event attendees.

---

remo/profiles/migrations/0060_merge_account.py

* Migrate events to the current account.
* Migrate reports to the current account.
* Migrate event attendance to the current account.
* Migrate polls to the current account.
* Migrate user status to the current account.
~~* Delete old user.~~

[fix bug 1240862] Merge two user accounts into one.

---

remo/reports/views.py

[fix bug 1262189] Raise 404 on all exceptions in list_reports.

---

remo/base/admin.py

Revert "List logs in admin."

---

docs/installation-docker.rst
docs/installation-virtualenv.rst

Update documentation for Django 1.8.

---

docs/installation-virtualenv.rst

Better structure virtualenv installation instructions.

---

bin/update/update.py
remo/settings/base.py

Add django-mozilla-product-details in installed apps.

---

remo/profiles/templates/admin/import_export/change_list_export.html
remo/settings/base.py

Add Celery check in profiles admin.

---

bin/update/update.py

Revert "Migrate djcelery."

---

remo/dashboard/templates/dashboard_reps.jinja
remo/remozilla/models.py

* Fixes unicode errors on dashboard.

Add a @property for Bug summary field.

---

remo/dashboard/templates/dashboard_reps.jinja
remo/remozilla/models.py

Revert "Add a @property for Bug summary field."

---

remo/remozilla/models.py

Revert "Add unicode_literal in Dashboard app."

---

.travis.yml

Use cache directive to speed up build time.

---

remo/reports/admin.py

@johngian happy reviewing! :beers:

NGReport export resource for the admin interface.

---

remo/profiles/models.py
remo/voting/models.py

Correctly revoke Celery tasks.

---

remo/voting/admin.py

@johngian r? 
With this small snippet we can revoke the celery tasks (if any) before deleting the objects.

Revoke celery tasks when a poll is deleted through admin.

---

remo/base/static/base/js/remolib.js

[fix bug 1283814] Decode search url on events page.

---

remo/voting/admin.py
remo/voting/tests/test_views.py
remo/voting/views.py

[fix bug 1282801] Delete bug when deleting a budget request poll.

---

remo/voting/templates/view_voting.jinja

[fix bug 1198134] Sort the results in range polls.

---

remo/voting/templates/view_voting.jinja
remo/voting/templates/vote_voting.jinja

Enable markdown syntax for poll description.

---

remo/voting/templates/vote_voting.jinja
remo/voting/views.py

* View voting
* Peers should be able to have read-only access to all votings
* Council should be able to have read-only access to `Review` votings
* List voting
* Peers should be able to list all votings
* Council should be able to also list `Review` votings.

Enhance voting functionality permissions

---

remo/base/templates/base_fd4.jinja

Fix `next' redirection url.

---

remo/api/urls.py
remo/base/urls.py
remo/dashboard/urls.py
remo/events/e_urls.py
remo/events/event_urls.py
remo/featuredrep/urls.py
remo/profiles/people_urls.py
remo/profiles/user_urls.py
remo/reports/r_urls.py
remo/reports/report_urls.py
remo/urls.py
remo/voting/models.py
remo/voting/v_urls.py

Update the url patterns in the project.

---

requirements/prod.txt

Upgrade django-jinja to version 2.2.1.

---

remo/events/templates/view_event.jinja

Revert "[833026] Multiple event attendees should be a grid"

---

remo/settings/base.py
requirements/prod.txt

Bump oidc version to 0.1.9.

---

remo/settings/base.py
requirements/prod.txt

* Temporarily disable logout from OP.

Bump oidc lib to version 0.1.10.

---

remo/base/static/base/css/app-fd4.less

https://bugzilla.mozilla.org/show_bug.cgi?id=1228433

[fix bug 1228433] Profile pics are squeezed for smaller resolutions

---

remo/settings/base_env_vars.py
requirements/prod.txt

I just added the bare minimum configuration for whitenoise

Add whitenoise support

---

remo/base/templates/labs.jinja

Temporarily remove link to mentorship diagram.

---

remo/settings/base_env_vars.py

`OIDC_OP_TOKEN_ENDPOINT` also defined twice

Remove Auth0 dev settings

---

bin/run-celery.sh
bin/run-prod.sh
remo/wsgi.py

- Run the correct wsgi
- Run migrations on the correct app

Fix Docker cmd scripts

---

Jenkinsfile

(did this on master branch the first time, bad idea)

Add Jenkinsfile for participation infrastructure

---

bin/bootstrap.sh
docker/prod

I'm not sure how nicely this will play with the `COMPRESS_ENABLED` setting since I'm forcing compression.

Compress assets at build time instead of runtime

---

remo/base/templates/base_fd4.jinja

Revert "Add warning banner about migration"

---

docker-compose.yml
env-dist

* Update database_url for docker env.
* Increase the value of max_allowed_packet in mysql.

Update docker file.

---

remo/base/tasks.py
remo/celery.py
remo/settings.py

* Notify healtchecks.io periodically to make sure that celery/celerybeat is up
and running

Improve celery monitoring.

---

remo/settings.py

@flamingspaz r?
This poll [0] was active for 5 days so I increased the limit to 7. Let's see if that helps.
[0] https://reps.mozilla.org/v/budget-request-flore-allemandou-https-reps-mozilla-org-e-write-the-docs/

Increase visibility timeout to 7 days.

---

remo/settings.py

* Remove deprecated celery configuration.

Fix typo in celery config.

---

remo/profiles/api/api_v1.py
remo/profiles/fixtures/initial_data.json
remo/profiles/migrations/0005_groups_new_resources_group.py
remo/profiles/templates/profiles_edit.jinja
remo/profiles/templates/profiles_people.jinja
remo/profiles/templates/profiles_view.jinja
remo/profiles/views.py
remo/voting/tests/__init__.py

We are currently training Resources Reps, and these need to be identifiable on the portal, so other Reps can reach out to them. See https://wiki.mozilla.org/ReMo/Resources for more info.

Add 'Resources' specialization as a group

---

remo/settings.py

Allow scripts from Django's admin in CSP.

---

remo/events/api/views.py

Bug 1326449 - Return events on API in descending order

---

remo/base/content_urls.py

Make Mobilising field values editable by Council

---

docs/installation-docker.rst
docs/installation-virtualenv.rst

Add test command to docs

---

remo/base/templates/multi_event_ical_template.jinja

https://bugzilla.mozilla.org/show_bug.cgi?id=1078094

Bug 1078094 - Always use UTC in iCal for events

---

remo/base/templates/base_fd4.jinja

[fix bug 1136513] Education menu added

---

remo/settings.py

Revert " Temporarily disable OIDC for debugging purposes."

---

README.md

Add Bugzilla ticket query to README

---

remo/reports/api/views.py

Followup fix from https://github.com/mozilla/remo/pull/1445/files

Order activities correctly as default is DESC already

---

docs/installation-virtualenv.rst
env-dist

Fix the hostname in connection url string for MySQL connection.
Also, updated an old comment to be correct :)
cc @MichaelKohler

fix(env): Fix sample env file to correctly work with MySQL

---

remo/events/api/api_v1.py
remo/events/views.py

This fixes: https://bugzilla.mozilla.org/show_bug.cgi?id=1411927
cc @MichaelKohler

Fix 1411927: Add default event ordering in v1 API

---

remo/base/tests/__init__.py
remo/settings.py
requirements/prod.txt

* Add the RefreshIDToken middleware.

Upgrade the mozilla-django-oidc lib to version 0.6.

---

remo/base/static/base/css/app-fd4.less
remo/base/templates/base_fd4.jinja

Update 'Join' modal according to Reps Council text

---

docs/profiles.rst
remo/profiles/templates/profiles_edit.jinja
remo/profiles/templates/profiles_view.jinja
remo/settings.py

Just had some fun.. this won't replace any values from the profiles, so most will still point to an IRC nickname ¯\_(ツ)_/¯

Replace IRC nickname and channels with Matrix
